# Generated by Django 2.0 on 2017-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_upload_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
