# Generated by Django 2.0 on 2017-12-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20171213_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
